#!/bin/bash
# Script to add iOS target to TrashPicUp project
# Run this script, then open the project in Xcode and verify the iOS target

echo "To add iOS support, please use Xcode:"
echo ""
echo "1. Open TrashPicUp.xcodeproj in Xcode"
echo "2. Click on the project in the navigator (top item)"
echo "3. Click the '+' button at the bottom of the targets list"
echo "4. Select 'iOS' > 'App'"
echo "5. Name it 'TrashPicUp iOS' (or similar)"
echo "6. Set Bundle Identifier: com.trashpicup.app.ios"
echo "7. Language: Swift, UI: SwiftUI"
echo "8. Click 'Finish'"
echo ""
echo "Then:"
echo "9. In the new iOS target's Build Phases, add all source files:"
echo "   - TrashPicUpApp.swift"
echo "   - ContentView.swift"
echo "   - PhotoManager.swift"
echo "   - PhotoAnalyzer.swift"
echo "   - GameView.swift"
echo "   - GameState.swift"
echo "   - AnalysisCache.swift"
echo "   - PlatformImage.swift"
echo "   - TrashPicUpTheme.swift"
echo ""
echo "10. Add Assets.xcassets to Resources"
echo "11. Set iOS Deployment Target to 17.0 (or your preferred version)"
echo "12. In Build Settings, set:"
echo "    - SDKROOT = iphoneos"
echo "    - TARGETED_DEVICE_FAMILY = 1,2 (iPhone and iPad)"
echo "    - IPHONEOS_DEPLOYMENT_TARGET = 17.0"
echo ""
echo "13. Add Info.plist key: NSPhotoLibraryUsageDescription"
echo "    Value: 'TrashPicUp needs access to your photo library to help you clean up unnecessary photos.'"
echo ""
echo "14. In Signing & Capabilities, add:"
echo "    - Photos Library (Read and Write)"
echo ""
echo "The code is already cross-platform with #if os(iOS) conditionals!"
